---

- hosts: localhost
  gather_facts: True

  tasks:
   - name: Fetch Java version
     shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
     changed_when: True
     register: java_result

   - debug:
       msg: "{{ java_result.stdout }}"