---

- hosts: localhost
  gather_facts: True

  tasks:
   - name: Fetch Java version
     shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
     changed_when: True
     register: java_result

   - debug:
       msg: "{{ java_result.stdout }}"
       
   - name: Check if java is installed
     command: java -version
     become_user: '{{ global_vars.user_session }}' // your user session
     register: java_result
     ignore_errors: True

   - debug:
          msg: "Failed - Java is not installed"
        when: java_result is failed
   - debug:
          msg: "Success - Java is installed"
        when:  java_result is success