- name: Check open JDK version and if not match install it
  hosts: all
  tasks:
  - name: install java        
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
      
  - name: Update path for maven use
    shell: export PATH=/usr/bin/java:$PATH