- name: Check open JDK version and if not match install it
  hosts: all
  tasks:
  - name: install java        
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
      
  - name: Update path for java use
    shell: export PATH=/usr/bin/java:$PATH
    
  - name: echo PATH
    shell: echo $PATH
    
  - name: Transfer executable Python script
    copy: src=Jenkins/jenkins.war dest=/opt/ansible_script mode=0777
    
  - name: Run Jenkins
    shell: java -jar jenkins.war