---
- hosts: ec2-user@ec2-18-223-3-189.us-east-2.compute.amazonaws.com
  remote_user: ec2-user
  strategy: free
  gather_facts: no
  tasks:
      - name: Echo task
        command: echo "File System check"

      - name: This command will show File System Details
        shell:
          cmd: df -khT
 
      - name: Create a directory if it does not exist
        file:
          path: /home/ec2-user/ansible_script
          state: directory
          mode: '0755'
          
      - name: Transfer executable script script
        copy: src=monitordisk.sh dest=/home/ec2-user/ansible_script mode=0777
 
      - name: Execute the script
        command: sh /home/ec2-user/ansible_script/monitordisk.sh {{ filesys }} {{ usage }}
        register: result

      - name: "Artifact Disk Check results to Tower Workflows"
        set_stats:
         data:
          diskcheck_result_ec1:  "{{ result.stdout }}"      