---
- hosts: ec2-user@ec2-54-159-136-238.compute-1.amazonaws.com
  sudo: true
  remote_user: ec2-user
  tasks:
      - name: Echo task
        command: echo "File System usage check"

      - name: This command will change the working directory to somedir/.
        shell:
          cmd: ls -l | grep log

      #- name: Transfer executable script
      #  copy: src=checkfilesystem.sh dest=/opt/ansible_script mode=0777

    #  - name: Execute the script
    #    command: sh /opt/ansible_script/checkfilesystem.sh

    #  - fetch:
    #      src: /opt/ansible_script/result.txt
      #      dest: /etc/tower

    #    - name: Remove sh and txt file from remote after copy in Ansible AWX
    #      shell: /bin/rm -rf /opt/ansible_script/*
