---
- hosts: ec2-user@ec2-18-223-3-189.us-east-2.compute.amazonaws.com
  remote_user: ec2-user
  tasks:
      - name: Echo task
        command: echo "File System check"

      - name: This command will shiw File System Details
        shell:
          cmd: df -khT
          
      - name: Print Host Name
        debug:
          var=ansible_hostname
 
      - name: Update modification and access time of given file
        file:
          path: /etc/some_file
          state: file
          modification_time: now
          access_time: now

          
      - name: Transfer executable script script
        copy: src=monitordisk.sh dest=/home/ec2-user/ansible_script mode=0777
 
      - name: Execute the script
        command: sh /home/ec2-user/ansible_script/monitordisk.sh      
     