---
- hosts: ec2-user@ec2-54-159-136-238.compute-1.amazonaws.com
  sudo: true
  remote_user: ec2-user
  tasks:
      - name: Echo task
        command: echo "File System check"

      - name: This command will shiw File System Details
        shell:
          cmd: df -Th
          
      - name: Print Host Name
        debug:
          var=ansible_hostname
          
      - name: "READ INPUT VARS"
        include_vars:
        file: "{{ input_file }}"
          
      #- name: Transfer executable script
      #  copy: src=checkfilesystem.sh dest=/opt/ansible_script mode=0777

    #  - name: Execute the script
    #    command: sh /opt/ansible_script/checkfilesystem.sh

    #  - fetch:
    #      src: /opt/ansible_script/result.txt
      #      dest: /etc/tower

    #    - name: Remove sh and txt file from remote after copy in Ansible AWX
    #      shell: /bin/rm -rf /opt/ansible_script/*
