---
- hosts: ec2-user@ec2-54-159-136-238.compute-1.amazonaws.com
  remote_user: ec2-user
  strategy: free
  gather_facts: no
  vars:
    - disk_result: "{{ diskcheck_result }}"

    - name: "Output test results"
      debug:
       msg: "{{ disk_result }}"