- name: Check open JDK version and if not match install it
  hosts: all
  tasks:
  - name: Create /opt directory
    file: path=/opt state=directory
  
  - name: Download Maven3
    get_url: dest=/opt/maven3.6.2.tar.gz url=http://apache.proserve.nl/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
  
  - name: Unpack Maven3
    action: command creates=/opt/maven chdir=/opt tar zxvf /opt/maven3.6.2.tar.gz

  - name: Create Maven3 directory link
    file: path=/opt/maven src=/opt/apache-maven-3.6.2 state=link
  
  - name: Set mvn link
    action: command update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1
    
  - name: Export Maven Path
    shell: export PATH=/usr/bin/java:$PATH
    
  - name: echo PATH
    shell: echo $PATH
    
  - name: Remove Maven3 archive
    file: path=/opt/maven3.6.2.tar.gz state=absent
